name: unece_unit_codes
description: "Dart package to support UNECE Unit Codes of Measure (UN/CEFACT Common Code for Units of Measure) according to the public specification."
version: 2.0.1
homepage: https://labfreed.org
repository: https://github.com/ApiniLabs/unece_unit_codes_dart
issue_tracker: https://github.com/ApiniLabs/unece_unit_codes_dart/issues
topics:
  - unece
  - unit-codes
  - units-of-measure
  - units


environment:
  sdk: ^3.9.2

dependencies:

dev_dependencies:
  test: ^1.26.3
  lints: ^6.0.0
