name: Release

on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Ensure the Dart code is formatted correctly
        run: dart format --set-exit-if-changed --output=none .

      - name: Run Dart analyze
        run: dart analyze

      - name: Run Dart tests
        run: dart test

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          makeLatest: true